#! /bin/bash
##############################################################
##
## Name		    :	deploy_muse_to_cluster
## Author	    :	Bradley Atkins
## Description	:	Deploy and install muse to a target
##			        cluster. Will install to all servers
##			        detailed in muse.hosts for that cluster
## Date		    :	16/05/2013
## Args		    :	
## Status	    :	Reviewed 	[n]
##			        Tested 		[n]
##			        Released 	[n]
##
##############################################################
error_exit()
{
	echo $1
	exit 1
}

#======================================
# Verification
#======================================
[[ $# -eq 1 ]] || error_exit "Usage: deploy_muse_to_cluster <cluster_FQDN>"

#======================================
# Setup
#======================================
MUSE_HOME="$(pwd)"
MHOSTS="${MUSE_HOME}/muse_root/user/muse.hosts"
MUSE_TAR=muse.tar
CLUSTER=$1

#======================================
# Confirm MUSe knows this cluster
#======================================
[[ $(sed -n '/'${CLUSTER}'/p' ${MHOSTS} | wc -l) -gt 0 ]] || error_exit "No entries found for cluster (${CLUSTER}) in (${MHOSTS})"
SERVER_LIST=$(sed -n '/'${CLUSTER}'/p' ${MHOSTS} | awk '{sl = sl" "$3}END{print sl}')
[[ -n ${SERVER_LIST} ]] || error_exit "Failed to recover server list from muse.hosts"

#======================================
# Create the indexes in the master db
#======================================
#muse_root/system/index_muse || error_exit "Failed to create indexes"

#======================================
# Create the tar ball
#======================================
[[ -f "${MUSE_HOME}/${MUSE_TAR}" ]] && rm -f "${MUSE_HOME}/${MUSE_TAR}"
tar zcvf ${MUSE_TAR} muse_root || error_exit "tar failed"

#======================================
# Copy it to firewall with installer
#======================================
scp -F ./ssh/ssh_config "${MUSE_HOME}/${MUSE_TAR}" ${CLUSTER}:. || error_exit "failed to scp tar file to cluster (${CLUSTER})"
scp -F ./ssh/ssh_config "${MUSE_HOME}/install_muse" ${CLUSTER}:. || error_exit "failed to scp installer to cluster (${CLUSTER})"
scp -F ./ssh/ssh_config "${MUSE_HOME}/deploy_muse_within_cluster" ${CLUSTER}:. || error_exit "failed to scp installer to cluster (${CLUSTER})"

ssh -F ./ssh/ssh_config ${CLUSTER} "chmod +w install_muse 2>/dev/null;chmod +w deploy_muse_within_cluster 2>/dev/null"
