#! /bin/bash
##############################################################
##
## Name		:	deploy_muse_within_cluster
## Author	:	Bradley Atkins
## Description	:	This file is copied to the firewall 
##			by deploy_muse_to_cluster  along with
##			install_muse and muse.tar. After 
##			deployment this script run fr4om the fwl
##			will install muse on every server in muse.hosts
## Date		:	16/05/2013
## Args		:	
## Status	:	Reviewed 	[n]
##			Tested 		[n]
##			Released 	[n]
##
##
##############################################################
error_exit()
{
    echo $1
    exit 1
}
LOG="/tmp/muse_deployment.log"
echo "$(date)" > ${LOG}
{

    #======================================
    # Verify usage
    #======================================
    [[ $# -eq 1 ]] || error_exit "Usage: args. cluster ID expected"

    #======================================
    # untar the muse.hosts file and
    # get our server list
    #======================================
    tar --extract --file=muse.tar muse_root/user/muse.hosts
    SERVER_LIST=$(sed -n '/'$1'/p' muse_root/user/muse.hosts | awk '{x = x" "$3}END{print x}')

    #======================================
    # Deploy the installer and tar ball
    # then run the installer
    #======================================
    echo "Server List = ${SERVER_LIST}"

    for SERVER in ${SERVER_LIST}
    do
        scp -o StrictHostKeyChecking=no muse.tar mailcontrol@${SERVER}:. || error_exit "SCP Failed for muse.tar ${SERVER}"
        scp -o StrictHostKeyChecking=no install_muse mailcontrol@${SERVER}:. || error_exit "SCP Failed for install muse ${SERVER}"

        printf "Installing MUSE on - %s\n" "${SERVER}"
        ssh -o StrictHostKeyChecking=no autotest@${SERVER} "cd ~mailcontrol;./install_muse 1>/dev/null;exit" & 
    done

    [[ -f muse_root/data/muse.hosts ]] && rm -rf muse_root

} | tee -a "${LOG}"
