#! /bin/bash
##############################################################
##
## Name         :   install_muse
## Author       :   Bradley Atkins
## Description  :   Install muse on the local server
## Date         :   28/08/2013
## Args         :   
## Status       :   Reviewed    [n]
##                  Tested      [n]
##                  Released    [n]
##
##
##############################################################
error_exit()
{
    echo "###################################"
    echo "Error: $(date):$1"
    echo "###################################"
    exit 1
} > /tmp/muse_install.log


if [[ -f muse.tar ]]
then
    #======================================
    # Remove existing and untar new
    #======================================
    sudo cp muse.tar /usr/local/bin || error_exit "Copy failed for muse.tar"
    cd /usr/local/bin || error_exit "cd failed to /usr/local/bin"
    [[ -d muse_root ]] && sudo rm -rf muse_root
    [[ -d muse_root ]]  && error_exit "Failed to delete existing root"
    sudo tar xvf muse.tar || error_exit "Untar failed for /usr/local/bin/muse.tar"
    sudo chown -R mailcontrol:mailcontrol /usr/local/bin/muse_root || error_exit "chown for muse root failed"
    
    [[ -f  /usr/local/bin/muse.tar ]] && sudo rm -f /usr/local/bin/muse.tar

    #======================================
    # Renew soft link
    #======================================
    [[ -L /usr/local/bin/muse ]] && sudo rm -f /usr/local/bin/muse
    [[ -L /usr/local/bin/slave ]] && sudo rm -f /usr/local/bin/slave
    #sudo ln -s /usr/local/bin/muse_root/system/muse /usr/local/bin/muse  || error_exit "Failed to create soft link"
    sudo ln -s /usr/local/bin/muse_root/master/system/master /usr/local/bin/muse  || error_exit "Failed to create soft link"
    sudo ln -s /usr/local/bin/muse_root/slave/system/slave /usr/local/bin/slave  || error_exit "Failed to create soft link"
    #sudo chown -R mailcontrol:mailcontrol /usr/local/bin/muse || error_exit "chown for soft link failed"

    #======================================
    # DEV directory
    #======================================
    sudo mkdir -p ~mailcontrol/.muse_dev || error_exit "failed to create muse_dev"
    sudo chown mailcontrol:mailcontrol ~mailcontrol/.muse_dev || error_exit "Chown 3 failed"

    ## TODO deprecate in favour of M_ROOT/environment
    sudo mkdir -p ~mailcontrol/muse_run_environment || error_exit "failed to create muse_run_environment"
    sudo chown mailcontrol:mailcontrol ~mailcontrol/muse_run_environment || error_exit "Chown 4 failed"

    #======================================
    # VIM RAD tools
    #======================================
    VIMRC="/usr/local/bin/muse_root/resources/vim/.muse_dev/.vimrc.custom"
    VIMFILES="/usr/local/bin/muse_root/resources/vim/vimfiles.tar"

    ## Install custom vimrc
    if [[ -f "${VIMRC}" ]] 
    then
        if [[ -d ~mailcontrol/.muse_dev ]]
        then
            for d in $(find ~mailcontrol/.muse_dev -type d)
            do
                sudo cp "${VIMRC}" ${d} || error_exit "Copy of custom vimrc to dev dir failed"
                sudo chown mailcontrol:mailcontrol ${d}/.vimrc.custom || error_exit "Chown failed for custom vimrc"
            done
        fi
        ## /tmp for muse -vif
        sudo cp "${VIMRC}" /tmp || error_exit "Copy of custom vimrc to tmp failed"
        sudo chown mailcontrol:mailcontrol /tmp/.vimrc.custom || error_exit "Chown failed for tmp custom vimrc"
    fi

    ## The vim templates
    if [[ -f "${VIMFILES}" ]] 
    then
        cd ~mailcontrol || error_exit "CD failed to ~mailcontrol"
        sudo cp "${VIMFILES}" ~mailcontrol/vimfiles.tar || error_exit "Failed to copy vim tar file"
        sudo tar xvf ~mailcontrol/vimfiles.tar || error_exit "Untar for .vimfiles failed"
        sudo chown mailcontrol:mailcontrol ~mailcontrol/.vim_files || error_exit "chown failed for vim files"
        sudo rm -f ~mailcontrol/vimfiles.tar 
    fi

    ## Point vimrc to our custom file
    if [[ ! -f ~mailcontrol/.vimrc ]]
    then
        sudo cp "/usr/local/bin/muse_root/resources/vim/.vimrc" ~mailcontrol || error_exit "Copy failed for .vimrc"
    fi

    if [[ -z $(grep "if filereadable" ~mailcontrol/.vimrc) ]]
    then
        sudo chmod a+w .vimrc || error_exit "chmod failed for .vimrc"
        sudo cat "/usr/local/bin/muse_root/resources/vim/.vimrc" >> .vimrc || error_exit "Failed to overwrite .vimrc"
    fi

    #======================================
    # musemsg home dir + ssh
    #======================================
    sudo mkdir -p /home/museslave/.ssh || error_exit "Failed to mkdir /home/museslave/.ssh"
    sudo chmod 700 /home/museslave/.ssh || error_exit "chmod failed for /home/museslave/.ssh"
    sudo chown museslave:mailcontrol /home/museslave/.ssh || error_exit "Chown failed for .ssh"
    sudo cp /usr/local/bin/muse_root/user/musemsg.key /home/museslave/.ssh || error_exit "copy failed for musemsg private key"
    sudo chmod 600 /home/museslave/.ssh/musemsg.key || error_exit "chmod failed for musemsg private key"
    sudo chown museslave:mailcontrol /home/museslave/.ssh/musemsg.key || error_exit "chmod failed for musemsg key"

    #======================================
    # Runtime directories etc
    #======================================
    sudo mkdir -p /var/tmp/muse/m_system || error_exit "Failed to create m_system"
    sudo chown mailcontrol:mailcontrol /var/tmp/muse/m_system || error_exit "chown m_system failed"
    sudo chmod a+w /var/tmp/muse/m_system || error_exit "chmod m_system failed"
    
    sudo mkdir -p /var/tmp/muse/run || error_exit "Failed to create run dir"
    sudo chown mailcontrol:mailcontrol /var/tmp/muse/run || error_exit "chown for run dir failed"
    sudo chmod a+w /var/tmp/muse/run || error_exit "chmod for run dir failed"

    sudo mkdir -p /var/log/muse || error_exit "Failed to create log dir"
    sudo chown mailcontrol:mailcontrol /var/log/muse || error_exit "chown for log dir failed"
    sudo chmod a+w /var/log/muse || error_exit "chmod for log dir failed"

else
    error_exit "muse.tar not found in current directory"
fi



