#! /bin/bash
##############################################################
##
## Name         :   Update Repo
## Author       :   Bradley Atkins
## Description  :   Use when pulling files back from a dev
##                  cluster that need to be chacked into CM
##                  Unpack tar file into subdir tmp
##                  delete tar file
##                  run this
##                  Then push
## Date         :   21/06/2015
## Args         :   
## Status       :   Reviewed    [n]
##                  Tested      [n]
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, version 2 only.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  
## USA
##
##############################################################
for f in $(ls tmp); do t=$(find muse_root -type f -name $f); p4 edit $t; done
for f in $(ls tmp); do t=$(find muse_root -type f -name $f); cp tmp/$f $t; done
for f in $(ls tmp); do t=$(find muse_root -type f -name $f); diff tmp/$f $t; done
