#! /bin/bash
# Unpack tar file into subdir tmp
# delete tar file
# run this
# Then submit
for f in $(ls tmp); do t=$(find muse_root -type f -name $f); p4 edit $t; done
for f in $(ls tmp); do t=$(find muse_root -type f -name $f); cp tmp/$f $t; done
for f in $(ls tmp); do t=$(find muse_root -type f -name $f); diff tmp/$f $t; done
