#! /bin/bash
##############################################################
##
## Name         :   get_hosts
## Author       :   Bradley Atkins
## Description  :   User should add code in here to retrieve
##                  host information and add it to muse.hosts
##                  in correct format. MUSE will then load the 
##                  host data into the master DB.
## Date         :   14/01/2015
## Args         :   
## Status       :   Reviewed    [n]
##                  Tested      [n]
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, version 2 only.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  
## USA
##
##############################################################
exit 0
