#! /bin/bash
##############################################################
##
## Name         :   m_test_run_host_2
## Author       :   Bradley Atkins
## Description  :   Test run host set by plugin run file
## Date         :   23/11/2014
## Args         :   
## Status       :   Reviewed    [n]
##                  Tested      [n]
##                  Released    [n]
##
## M_JOB_HOST M_RUN_HOST
## M_GREP_PATTERN "^[[:alnum:]]+: |^/.*: |error|info|warning"
##
##############################################################
SCRIPT_NAME=m_test_run_host_2

hostname

